config/routes.rb
MicroOJ::Application.routes.draw do
    resources :problems
    resources :solutions
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    root    'static_pages#home'
    match   '/help',            to: 'static_pages#help',    via: 'get'
    match   '/about',           to: 'static_pages#about',   via: 'get'
    match   '/new_problem',     to: 'problems#new',         via: 'get'
    match   '/show_problems',   to: 'problems#show',        via: 'get'
    match   '/signup',          to: 'users#new',            via: 'get'
    match   '/signin',          to: 'sessions#new',         via: 'get'
    match   '/signout',         to: 'sessions#destroy',     via: 'delete'

  

end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="row-fluid">
    <footer class="footer">
    <small>
        <a href="http://rendon.x10.mx/">Inforscience</a>
        (C) Rafael Rendón Pablo
    </small>
    <nav>
    <ul>
        <li><%= link_to "Acerca de",   about_path %></li>
    </ul>
    </nav>
    </footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
    <div class="container">
        <%= link_to "Micro OJ", root_path, class: "brand" %>
        <nav>
        <ul class="nav pull-left">
            <li><%= link_to "Inicio",    root_path %></li>
            <li><%= link_to "Ayuda",     help_path %></li>
            <li><%= link_to "Acerca de", about_path%></li>
        </ul>

        <ul class="nav pull-right">
            <% if signed_in? %>
                <li id="fat-menu" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Mi cuenta
                    </a>

                    <ul class="dropdown-menu">
                        <li><%= link_to "Perfil",
                            users_path + "/" + current_user.id.to_s %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Salir", signout_path, method:"delete"%>
                    </ul>
                </li>
            <% else %>
                <li><%= link_to "Registrarse", signup_path %></li>
                <li><%= link_to "Iniciar sesión", signin_path %></li>
            <% end %>
        </ul>

        </nav>
    </div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<!-- Side bar -->
<div class="span3">
    <div class="well sidebar-nav">
        <ul class="nav nav-list">
            <% if signed_in? and current_user.name == ADMIN_USER %>
                <li>
                <%= link_to "Crear problemas", new_problem_path %>
                </li>
            <% end %>
            <li> <%= link_to "Problemas", problems_path %></li>
            <li> <%= link_to "Usuarios", users_path %></li>
        </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Header -->
    <%= render 'layouts/header' %>

    <!-- Main layout -->
    <div class="container">
        <div class="container-fluid">
            <div class="row-fluid">

                <!-- Side bar -->
                <%= render 'layouts/sidebar' %>

                <!-- Main content -->
                <div class="span8">
                    <% flash.each do |key, value| %>
                        <div class="alert alert-<%= key %>"><%= value %></div>
                    <% end %>

                    <%= yield %>
                </div>
            </div>

            <!-- Footer -->
            <%= render 'layouts/footer' %>
            <%= debug(params) if Rails.env.development? %>
        </div>
    </div>
</body>
</html>